/* js/chart.js — the character chart.
   One of the classic scripts index.html loads in order; see CLAUDE.md, "Scripts". */
"use strict";

/* ---------- character chart ---------- */
const add = (parent, tag, cls, text) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text != null) n.textContent = text;
  parent.appendChild(n);
  return n;
};

// Readings come from the decks wherever a kana is drilled, so the chart's
// layout data and the quiz can never disagree. A flow item may carry its own
// `a` — the extended katakana are reference-only and in no deck.
function chartReadings() {
  const map = new Map();
  state.decks.forEach((d) => d.cards.forEach((c) => {
    if (!map.has(c.q)) map.set(c.q, c.a);
  }));
  return map;
}

function kanaCell(parent, q, romaji) {
  const cell = add(parent, "span", "kcell");
  add(cell, "span", "kcell__k", q).lang = "ja";
  add(cell, "span", "kcell__r", romaji);
  return cell;
}

function renderChart(id) {
  const chart = state.charts.find((c) => c.id === id) || state.charts[0];
  if (!chart) return;
  const readings = chartReadings();
  const readingOf = (item) =>
    typeof item === "string" ? (readings.get(item) || "?") : (item.a || readings.get(item.q) || "?");
  const kanaOf = (item) => (typeof item === "string" ? item : item.q);

  el.chart.dataset.script = chart.id;
  Array.from(el.chartSwitch.children).forEach((b) =>
    b.setAttribute("aria-checked", String(b.dataset.chart === chart.id)));

  el.chartBody.innerHTML = "";
  const mast = add(el.chartBody, "div", "chart__masthead");
  add(mast, "h3", null, chart.ja).lang = "ja";
  add(mast, "p", null, chart.subtitle || chart.label);

  chart.sections.forEach((sec) => {
    const block = add(el.chartBody, "section", "chart__block");
    const h = add(block, "h4", null, sec.title);
    if (sec.en) add(h, "span", "en", sec.en);

    if (sec.type === "flow") {
      const flow = add(block, "div", "chart--flow");
      (sec.items || []).forEach((item) => kanaCell(flow, kanaOf(item), readingOf(item)));
      return;
    }

    // Numbers are the one chart whose readings cannot be looked up — there is
    // no deck of them to look them up *from* — so an item carries all three
    // parts itself. What keeps it honest is that the shipped entries were
    // generated by readNumber(), not typed; the suite regenerates them and
    // fails if the file has drifted.
    if (sec.type === "numbers") {
      // `wide` is one item per row, for readings too long to sit beside
      // another — 12,345 is eighteen kana.
      const list = add(block, "div", "chart--num" + (sec.wide ? " chart--num--wide" : ""));
      (sec.items || []).forEach((item) => {
        const row = add(list, "div", "nrow");
        // Four facts, three columns: the leading cell carries both what the
        // row is — 6, Monday, the 20th — and how that is written, which is
        // what the drill now shows. `x` is optional, so a chart that has no
        // written form for a row simply names it.
        const lead = add(row, "span", "nrow__n");
        // the calendar table is written the way the Dates setting says —
        // 4時20分 or 四時二十分 — so it matches the square beside it
        const x = item.x && chart.id === "calendar" && state.dates === "numeral"
          ? numeralText(item.x) : item.x;
        if (x) add(lead, "span", "nrow__x", x).lang = "ja";
        add(lead, "span", "nrow__id", item.n);
        add(row, "span", "nrow__k", item.q).lang = "ja";
        add(row, "span", "nrow__r", item.a);
      });
      return;
    }

    const table = add(block, "table", "chart");
    const headRow = add(add(table, "thead"), "tr");
    add(headRow, "th", null, "").setAttribute("aria-hidden", "true");   // corner
    sec.cols.forEach((c) => { add(headRow, "th", null, c).scope = "col"; });

    const body = add(table, "tbody");
    sec.rows.forEach((row) => {
      const tr = add(body, "tr");
      add(tr, "th", null, row.label).scope = "row";
      sec.cols.forEach((_, idx) => {
        const q = row.cells[idx];
        const td = add(tr, "td", q ? null : "is-gap");
        if (q) kanaCell(td, q, readings.get(q) || "?");
      });
    });

    // the final nasal stands alone rather than pretending to be an a-column
    if (sec.single) {
      const solo = add(block, "div", "chart--single");
      kanaCell(solo, sec.single, readings.get(sec.single) || "?");
    }
  });

  // The seal and the line beside it belong to the chart, not to the sheet:
  // "rows follow the gojūon ordering" is false of a table of numbers. The
  // two kana charts carry neither and keep what they always said.
  const note = add(el.chartBody, "p", "chart__note");
  add(note, "span", "chart__seal", chart.seal || "五十音").lang = "ja";
  add(note, "span", "chart__notetext",
      chart.note || "Rows follow the standard gojūon ordering.");
}

function openChart() {
  // opens on whichever script the menu is showing
  renderChart(state.script);
  navTo(el.chart);
  el.chartBody.focus();     // so arrow keys / space scroll the tables
}
